export default [
  {
    key: '1',
    sn: 1,
    name: 'Frontiers of Science Awards',
    date: 2023,
    level: '<strong>International Congress of Basic Science (ICBS)</strong>',
  },
  {
    key: '2',
    sn: 2,
    name: 'Nomination for the Distinguished Paper Award',
    date: 2020,
    level: '<strong>CCS’2020</strong>',
  },
  {
    key: '3',
    sn: 3,
    name: '无连接网络中安全可信的端到端传送关键技术及应用',
    date: 2022,
    level: '电子学会科技进步一等奖',
  },
  {
    key: '4',
    sn: 4,
    name: '自主可控安全可信体系结构及关键技术',
    date: 2020,
    level: '省部级科技进步二等奖',
  },
  {
    key: '5',
    sn: 5,
    name: 'BKG2015DX2010',
    date: 2015,
    level: '省部级科技进步二等奖',
  },
  {
    key: '6',
    sn: 6,
    name: '面向互联网域间路由系统的大规模流量分析技术研究',
    date: 2018,
    level: '省部级科技进步二等奖',
  },
  {
    key: '7',
    sn: 7,
    name: '网络安全与抗毁生存测试验证技术',
    date: 2017,
    level: '省部级科技进步二等奖',
  },
  {
    key: '8',
    sn: 8,
    name: '网络安全态势感知技术',
    date: 2011,
    level: '省部级科技进步二等奖',
  },
  {
    key: '9',
    sn: 9,
    name: '可重构的大规模 IP 网络试验环境构建技术',
    date: 2013,
    level: '省部级科技进步二等奖',
  },
  {
    key: '10',
    sn: 10,
    name: '清华大学优秀博士毕业生',
    date: 2022,
    level: '',
  },
  {
    key: '11',
    sn: 11,
    name: '清华大学优秀博士学位论文',
    date: 2022,
    level: '',
  },
  {
    key: '12',
    sn: 12,
    name: 'ACM SIGSAC China优博奖',
    date: 2022,
    level: '',
  },
  {
    key: '13',
    sn: 13,
    name: '省部级优秀硕士学位论文',
    date: 2011,
    level: '',
  },
]