name: Deploy GitHub Pages site
permissions:
  contents: read
  pages: write
  id-token: write
on:
  push:
    branches:
      - dev # 触发部署的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16 # 指定 Node.js 版本

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: github-pages # Make sure this matches the artifact_name in deploy step
      #     path: ./dist
          
      # - name: Deploy to GitHub Pages
      #   uses: actions/deploy-pages@v1.2.9
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub Token 进行部署
      
      - name: Push dist to original branch
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
          git checkout dev # 切换到原始分支，这里假设原始分支是 dev，请根据实际情况修改
          git merge --no-commit --no-ff ${{ github.sha }} # 将构建的内容合并到原始分支，但不要自动提交
          mv dist/* . # 将构建的内容移动到仓库根目录，根据实际情况修改
          git add .
          git commit -m "Update website" # 提交更改
          git push origin dev # 推送更改到原始分支
      
        

